### PR TITLE
fUpdate passwords.lst

### PR DESCRIPTION
**Pull request by mohsen2002**

### CODE REVIEW

**Comment by 4lxprime** [comment]
lmao, can i ask why this change ?

**Comment by mohsen2002** [comment]
Because I have a desire to try the tool on a specific account and how it
detects the code
mohsenalfadle

في الأحد، ٢١ تموز ٢٠٢٤ ٤:٠٧ م 4lxprime ***@***.***> كتب:

**Comment by mohsen2002** [comment]
Does the tool work? If it detects the code, does the color change?
mohsenalfadle

في الأحد، ٢١ تموز ٢٠٢٤ ٥:٣٤ م Mohsen Lateef ***@***.***> كتب:

**Comment by 4lxprime** [comment]
The tool may not work properly, the color doesn't change as i remember but if something was found, it should stop and log the good one. Moreover you don't need to add the password you wanted to test in the git but you can do that locally on your computer or you can also provide your own wordlist and rename it passwords.lst.

**Pull request closed without merging**
